# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b75c12aba5187dabefdd4a1ffcbb65f078c194d60d7c09ae64747751108282773a1db02af1f710932f40d4a981d2917a37e719ef4699022943bc9af972b34de

test:
  secret_key_base: d934507fedf06760c7b4480e4b990399224728c9f96c01fcb06b330202bf5c75c26b4e52a2d90f9e0a0164b4635a4e99db0fbbb1e2049a389652bfeec521f5eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
